## ML Project: Analysis with Pandas, Student Academic Performance

By: Laureen Otieno
laurnadhiambo@gmail.com

10th April 2025

### STEP 1: Import Pandas as pd

In [42]:
import pandas as pd

### STEP 2: import data from github

In [50]:
url = "https://raw.githubusercontent.com/ritaafrica/data/refs/heads/main/student_scores.csv"
df = pd.read_csv(url)
df.head()

,StudentID,Name,Country,Gender,Age,Math_Score,Reading_Score,Writing_Score,School,Class
0,1,Ifeanyi Mugisha,Zimbabwe,Female,18,99,77,12,Nelson Mandela School,JSS1
1,2,Yemi Okeke,Tanzania,Male,16,60,29,98,Ubuntu Academy,JSS2
2,3,Fatou Mugisha,Zimbabwe,Male,15,49,46,84,Ubuntu Academy,SS3
3,4,Chinedu Okafor,Ethiopia,Female,17,34,57,45,Ubuntu Academy,SS2
4,5,Yemi Moyo,Senegal,Male,16,22,16,38,Ubuntu Academy,SS3

### STEP 3: Add new column called "Total scores" to the dataset

In [28]:
df ["Status"] = "Pending" # demo

In [51]:
df.head()

,StudentID,Name,Country,Gender,Age,Math_Score,Reading_Score,Writing_Score,School,Class
0,1,Ifeanyi Mugisha,Zimbabwe,Female,18,99,77,12,Nelson Mandela School,JSS1
1,2,Yemi Okeke,Tanzania,Male,16,60,29,98,Ubuntu Academy,JSS2
2,3,Fatou Mugisha,Zimbabwe,Male,15,49,46,84,Ubuntu Academy,SS3
3,4,Chinedu Okafor,Ethiopia,Female,17,34,57,45,Ubuntu Academy,SS2
4,5,Yemi Moyo,Senegal,Male,16,22,16,38,Ubuntu Academy,SS3

In [12]:
df ["Total_Scores"] = df["Math_Score"] + df["Reading_Score"] + df["Writing_Score"]

In [52]:
df.head()

,StudentID,Name,Country,Gender,Age,Math_Score,Reading_Score,Writing_Score,School,Class
0,1,Ifeanyi Mugisha,Zimbabwe,Female,18,99,77,12,Nelson Mandela School,JSS1
1,2,Yemi Okeke,Tanzania,Male,16,60,29,98,Ubuntu Academy,JSS2
2,3,Fatou Mugisha,Zimbabwe,Male,15,49,46,84,Ubuntu Academy,SS3
3,4,Chinedu Okafor,Ethiopia,Female,17,34,57,45,Ubuntu Academy,SS2
4,5,Yemi Moyo,Senegal,Male,16,22,16,38,Ubuntu Academy,SS3

### STEP 4: Calculate the percentage_scores

In [22]:
df ["percentage_scores"] = df ["Total Scores"] /300*100
df ["percentage_scores"] = round(df ["Total Scores"] /300*100) # to roundoff

In [55]:
df.head()

,StudentID,Name,Country,Gender,Age,Math_Score,Reading_Score,Writing_Score,School,Class
0,1,Ifeanyi Mugisha,Zimbabwe,Female,18,99,77,12,Nelson Mandela School,JSS1
1,2,Yemi Okeke,Tanzania,Male,16,60,29,98,Ubuntu Academy,JSS2
2,3,Fatou Mugisha,Zimbabwe,Male,15,49,46,84,Ubuntu Academy,SS3
3,4,Chinedu Okafor,Ethiopia,Female,17,34,57,45,Ubuntu Academy,SS2
4,5,Yemi Moyo,Senegal,Male,16,22,16,38,Ubuntu Academy,SS3

### STEP 5: Rename Math_Score to Mathematics_Score

In [24]:
df.rename(columns={"Math_Score" : "Mathematics_Score"}, inplace=True)

In [56]:
df.head()

,StudentID,Name,Country,Gender,Age,Math_Score,Reading_Score,Writing_Score,School,Class
0,1,Ifeanyi Mugisha,Zimbabwe,Female,18,99,77,12,Nelson Mandela School,JSS1
1,2,Yemi Okeke,Tanzania,Male,16,60,29,98,Ubuntu Academy,JSS2
2,3,Fatou Mugisha,Zimbabwe,Male,15,49,46,84,Ubuntu Academy,SS3
3,4,Chinedu Okafor,Ethiopia,Female,17,34,57,45,Ubuntu Academy,SS2
4,5,Yemi Moyo,Senegal,Male,16,22,16,38,Ubuntu Academy,SS3

### STEP 6: Rename Gender to G

In [57]:
df.rename(columns={"Gender" : "G"}, inplace=True)
df.head()

,StudentID,Name,Country,G,Age,Math_Score,Reading_Score,Writing_Score,School,Class
0,1,Ifeanyi Mugisha,Zimbabwe,Female,18,99,77,12,Nelson Mandela School,JSS1
1,2,Yemi Okeke,Tanzania,Male,16,60,29,98,Ubuntu Academy,JSS2
2,3,Fatou Mugisha,Zimbabwe,Male,15,49,46,84,Ubuntu Academy,SS3
3,4,Chinedu Okafor,Ethiopia,Female,17,34,57,45,Ubuntu Academy,SS2
4,5,Yemi Moyo,Senegal,Male,16,22,16,38,Ubuntu Academy,SS3

### STEP 7: Remove/ delete the "School" column

In [58]:
df.drop(columns=["School"], inplace=True)
df.head()

,StudentID,Name,Country,G,Age,Math_Score,Reading_Score,Writing_Score,Class
0,1,Ifeanyi Mugisha,Zimbabwe,Female,18,99,77,12,JSS1
1,2,Yemi Okeke,Tanzania,Male,16,60,29,98,JSS2
2,3,Fatou Mugisha,Zimbabwe,Male,15,49,46,84,SS3
3,4,Chinedu Okafor,Ethiopia,Female,17,34,57,45,SS2
4,5,Yemi Moyo,Senegal,Male,16,22,16,38,SS3

### STEP 8: save the dataset to csv

In [34]:
df.to_csv("modified_student_scores.csv", index=False)

In [35]:
df.head()

,StudentID,Name,Country,G,Age,Mathematics_Score,Reading_Score,Writing_Score,Class,Status,Total Scores,percentage_scores
0,1,Ifeanyi Mugisha,Zimbabwe,Female,18,99,77,12,JSS1,Pending,188,63.0
1,2,Yemi Okeke,Tanzania,Male,16,60,29,98,JSS2,Pending,187,62.0
2,3,Fatou Mugisha,Zimbabwe,Male,15,49,46,84,SS3,Pending,179,60.0
3,4,Chinedu Okafor,Ethiopia,Female,17,34,57,45,SS2,Pending,136,45.0
4,5,Yemi Moyo,Senegal,Male,16,22,16,38,SS3,Pending,76,25.0